/*
 * This file is generated by jOOQ.
 */
package com.apress.demo.jooq.domain;


import com.apress.demo.jooq.domain.tables.Comments;
import com.apress.demo.jooq.domain.tables.Posts;
import com.apress.demo.jooq.domain.tables.records.CommentsRecord;
import com.apress.demo.jooq.domain.tables.records.PostsRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CommentsRecord> CONSTRAINT_A = Internal.createUniqueKey(Comments.COMMENTS, DSL.name("CONSTRAINT_A"), new TableField[] { Comments.COMMENTS.ID }, true);
    public static final UniqueKey<PostsRecord> CONSTRAINT_4 = Internal.createUniqueKey(Posts.POSTS, DSL.name("CONSTRAINT_4"), new TableField[] { Posts.POSTS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CommentsRecord, PostsRecord> CONSTRAINT_AB = Internal.createForeignKey(Comments.COMMENTS, DSL.name("CONSTRAINT_AB"), new TableField[] { Comments.COMMENTS.POST_ID }, Keys.CONSTRAINT_4, new TableField[] { Posts.POSTS.ID }, true);
}
