/*
 * This file is generated by jOOQ.
 */
package com.apress.demo.jooq.domain;


import com.apress.demo.jooq.domain.tables.Comments;
import com.apress.demo.jooq.domain.tables.Posts;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.COMMENTS</code>.
     */
    public final Comments COMMENTS = Comments.COMMENTS;

    /**
     * The table <code>PUBLIC.POSTS</code>.
     */
    public final Posts POSTS = Posts.POSTS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Comments.COMMENTS,
            Posts.POSTS
        );
    }
}
