/*
 * This file is generated by jOOQ.
 */
package com.apress.demo.jooq.domain.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum PostsPostStatus implements EnumType {

    DRAFT("DRAFT"),

    PUBLISHED("PUBLISHED");

    private final String literal;

    private PostsPostStatus(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "POSTS_POST_STATUS";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static PostsPostStatus lookupLiteral(String literal) {
        return EnumType.lookupLiteral(PostsPostStatus.class, literal);
    }
}
